SELECT
    CONCAT(FIRST_NAME, ' ', MIDDLE_NAME, ' ', LAST_NAME) AS FULL_NAME
    ,EMAIL_ADDRESS
    ,MOBILE_NUMBER
    ,BIRTH_DATE,
    TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) AS DATE
FROM "BPAY_SFCPLUS_accounts"
WHERE
-- TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) = CURRENT_DATE
TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) = :DailyRegis