SELECT 
    -- Schedule info ( "BPAY_SMDC_recurring_payments")
    RP.PROPERTY_ID,
    RP.CURRENCY,
    ROUND(RP.AMOUNT*1.0/100,2) AS AMOUNT,
    TO_CHAR(RP.START_DATE, 'MM/DD/YYYY') AS START_DATE,
    TO_CHAR(RP.END_DATE, 'MM/DD/YYYY') AS END_DATE,
    INSTALLMENT_COUNT,
    FREQUENCY,
    SCHEDULED_DATE AS NEXT_SCHEDULED_DAY,
    EXTRACT(DAY FROM SCHEDULED_DATE) AS SCHEDULE_DAY,

    -- Payment info ( BPAY_SMDC_PAYMENTS)
    TO_CHAR(PAYMENTS.CREATED_AT, 'MM/DD/YYYY') AS LAST_PAYMENT_DATE,
    ROUND(PAYMENTS.FEES_AMOUNT*1.0/100,2) AS LAST_PAYMENT_FEES_AMOUNT,
    PAYMENTS.FEES_CURRENCY AS LAST_PAYMENT_FEES_CURRENCY,
    ROUND(PAYMENTS.TOTAL_AMOUNT*1.0/100,2) AS LAST_PAYMENT_TOTAL_AMOUNT,
    
    -- Payment results ( BPAY_SMDC_TRANSACTIONS )
    PAYMENTS.TRANSACTION_STATUS, -- STATUS
    TRANSACTION_CODE,
    ROUND(TRANSACTION_AMOUNT*1.0/100,2) AS TRANSACTION_AMOUNT,
    TRANSACTION_CURRENCY,
    ROUND(TRANSACTION_AMOUNT_LANDED*1.0/100,2) AS TRANSACTION_AMOUNT_LANDED,
    TRANSACTION_CURRENCY_LANDED,
    TRANSACTION_DATE,

    -- Property info ( BPAY_SMDC_PROPERTIES)
    P.CIN AS CIN,
    P.NAME AS PROPERTY_NAME,
    P.UNIT AS PROPERTY_UNIT,
    P.BUYERS_NAME,

    -- Customer info
    C.ID AS CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    C.EMAIL_ADDRESS,
    C.MOBILE_NUMBER
    
FROM "BPAY_SMDC_recurring_payments" RP
    LEFT OUTER JOIN(
        SELECT
            --"BPAY_SMDC_payments"
            PROPERTY_ID,
            TYPE,
            GATEWAY,
            CHANNEL,
            P.AMOUNT,
            P.CURRENCY,
            DUE_DATE,
            P.CREATED_AT,
            REFERENCE_ID,
            FEES_AMOUNT,
            FEES_CURRENCY,
            TOTAL_AMOUNT,

            
            T.STATUS AS TRANSACTION_STATUS,
            T.CODE AS TRANSACTION_CODE,
            T.AMOUNT AS TRANSACTION_AMOUNT,
            T.CURRENCY AS TRANSACTION_CURRENCY,
            T.AMOUNT_LANDED AS TRANSACTION_AMOUNT_LANDED,
            T.CURRENCY_LANDED AS TRANSACTION_CURRENCY_LANDED,
            TO_CHAR(T.CREATED_AT,'MM/DD/YYYY') AS TRANSACTION_DATE
        FROM "BPAY_SMDC_payments" P
            LEFT OUTER JOIN (
                SELECT
                    STATUS,
                    CODE,
                    AMOUNT,
                    CURRENCY,
                    AMOUNT_LANDED,
                    CURRENCY_LANDED,
                    CREATED_AT,
                    PAYMENT_ID
                FROM SFC_ISDA.SFC_BRONZE."BPAY_SMDC_transactions"T
                    WHERE T.CREATED_AT = (SELECT MAX(TT.CREATED_AT) FROM "BPAY_SMDC_transactions"TT 
                            WHERE TT.PAYMENT_ID = T.PAYMENT_ID)) T ON P.ID = T.PAYMENT_ID
                WHERE 
                    P.CREATED_AT = (SELECT MAX(CREATED_AT) FROM "BPAY_SMDC_payments"PP WHERE P.PROPERTY_ID = PP.PROPERTY_ID)) PAYMENTS
                ON 
                    PAYMENTS.PROPERTY_ID = RP.ID
                LEFT OUTER JOIN "BPAY_SMDC_properties" P ON RP.PROPERTY_ID = P.ID
                LEFT OUTER JOIN "BPAY_SMDC_customers" C ON P.CUSTOMER_ID = C.ID
WHERE
    RP.DELETED_AT IS NULL
    AND FREQUENCY = 'M';
ORDER BY
    CASE WHEN EXTRACT( DAY FROM SCHEDULED_DATE) >= EXTRACT( DAY FROM CURRENT_TIME)
    THEN EXTRACT( DAY FROM SCHEDULED_DATE) - 31
    ELSE EXTRACT( DAY FROM RP.SCHEDULED_DATE) END DESC;