with C as (
    SELECT 
        DATE_PART(Week, REPLACE(REPLACE(DATETIME, 'AM', ''), 'PM', '')::TIMESTAMP) AS WEEK_COUNT,
        TO_CHAR(DATE_TRUNC('WEEK', REPLACE(REPLACE(DATETIME, 'AM', ''), 'PM', '')::TIMESTAMP)::DATE, 'MM/DD/YYYY') AS WEEK_OF,
        SUM(CASE WHEN CUST_ID IS NOT NULL THEN 1 ELSE 0 END) AS MEMBER_COUNT,
        SUM(CASE WHEN CUST_ID IS NULL THEN 1 ELSE 0 END) AS NON_MEMBER_COUNT
    FROM EPT_STRFD_REGISTER_HEADER
    WHERE (CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%') OR CUST_ID IS NULL
    GROUP BY 
        WEEK_COUNT,
        WEEK_OF
),B as (
    SELECT 
        DATE_PART(Week, REPLACE(REPLACE(DATETIME, 'AM', ''), 'PM', '')::TIMESTAMP) AS WEEK_COUNT,
        TO_CHAR(DATE_TRUNC('WEEK', REPLACE(REPLACE(DATETIME, 'AM', ''), 'PM', '')::TIMESTAMP)::DATE, 'MM/DD/YYYY') AS WEEK_OF,
        COUNT(*) AS NUMBER_OF_TRANSACTIONS,
    FROM EPT_STRFD_REGISTER_HEADER
    WHERE (CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%') OR CUST_ID IS NULL
    GROUP BY
        WEEK_COUNT,
        WEEK_OF
), A AS (
    SELECT 
        DATE_PART(Week, REPLACE(REPLACE(DATETIME, 'AM', ''), 'PM', '')::TIMESTAMP) AS WEEK_COUNT,
        TO_CHAR(DATE_TRUNC('WEEK', REPLACE(REPLACE(DATETIME, 'AM', ''), 'PM', '')::TIMESTAMP)::DATE, 'MM/DD/YYYY') AS WEEK_OF,
        COUNT(*) AS UNIT_SOLD,
        SUM(TOTAL) AS TOTAL_TRANSACTION_AMOUNT,
    FROM EPT_STRFD_REGISTER_TRANS RT
    WHERE (CARD_NO LIKE '83%' AND CARD_NO NOT LIKE '%XXXXX%') OR CARD_NO IS NULL
    GROUP BY 
        WEEK_COUNT,
        WEEK_OF
)
SELECT
    A.WEEK_COUNT,
    A.WEEK_OF,
    A.UNIT_SOLD / B.NUMBER_OF_TRANSACTIONS AS AVG_BASKET_SIZE,
    A.TOTAL_TRANSACTION_AMOUNT / B.NUMBER_OF_TRANSACTIONS AS AVG_TOTAL_AMOUNT,
    C.MEMBER_COUNT,
    C.NON_MEMBER_COUNT
FROM A
INNER JOIN B 
    ON A.WEEK_COUNT = B.WEEK_COUNT
    AND A.WEEK_OF = B.WEEK_OF
INNER JOIN C 
    ON A.WEEK_COUNT = C.WEEK_COUNT
    AND A.WEEK_OF = C.WEEK_OF
ORDER BY A.WEEK_COUNT;

