WITH DUPE_HEADER AS (
    SELECT 
        PROC_DATE, DATETIME, 
        EMP_NO, TILL_NO, 
        CUST_ID, TOTAL, 
        TOT_ITEMS, POINTS_EARNED, 
        TOT_ITEMS_SCANNED,
        MAX(INGESTED_DATE)
    FROM 
        EPT_STRFD_REGISTER_HEADER 
    GROUP BY
        PROC_DATE, 
        DATETIME, EMP_NO, 
        TILL_NO, CUST_ID, 
        TOTAL, TOT_ITEMS, 
        POINTS_EARNED, TOT_ITEMS_SCANNED
) 
SELECT 
    DATE_PART(Week, REPLACE(REPLACE(DATETIME, 'AM', ''), 'PM', '')::TIMESTAMP) AS WEEK_COUNT,
    TO_CHAR(DATE_TRUNC('WEEK', REPLACE(REPLACE(DATETIME, 'AM', ''), 'PM', '')::TIMESTAMP)::DATE, 'MM/DD/YYYY') AS WEEK_OF,
    SUM(TOT_ITEMS) / SUM(CASE WHEN (CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%') OR CUST_ID IS NULL THEN 1 ELSE 1 END) AS AVG_BASKET_SIZE,
    SUM(CASE WHEN CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%' THEN TOT_ITEMS ELSE 1 END) / SUM(CASE WHEN CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%' THEN 1 ELSE 0 END) AS AVG_BASKET_SIZE_MEMBER,
    SUM(CASE WHEN CUST_ID IS NULL THEN TOT_ITEMS ELSE 0 END) / SUM(CASE WHEN CUST_ID IS NULL THEN 1 ELSE 1 END) AS AVG_BASKET_SIZE_NON_MEMBER
    -- SUM(TOTAL) / SUM(CASE WHEN (CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%') OR CUST_ID IS NULL THEN 1 ELSE 1 END) AS AVG_BASKET_AMOUNT
    -- SUM(CASE WHEN CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%' THEN TOTAL ELSE 0 END) / SUM(CASE WHEN CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%' THEN 1 ELSE 0 END) AS AVG_BASKET_AMOUNT_MEMBER,
    -- SUM(CASE WHEN CUST_ID IS NULL THEN TOTAL ELSE 0 END) / SUM(CASE WHEN CUST_ID IS NULL THEN 1 ELSE 1 END) AS AVG_BASKET_AMOUNT_NON_MEMBER
FROM 
    DUPE_HEADER
WHERE
    (CUST_ID LIKE '83%' AND CUST_ID NOT LIKE '%XXXXX%') OR CUST_ID IS NULL
    -- CUST_ID = '8366880002314983' 
    -- AND DATETIME LIKE '1/27/2025 %'
GROUP BY
    WEEK_COUNT,
    WEEK_OF;

select * from SFC_ISDA.SFC_BRONZE.SFC_PLUS_STORES
where STORE_NAME Like '%Scarborough%';