SELECT * FROM SFC_ISDA.SFC_BRONZE.SFC_PLUS_CPOINTS;

ALTER SESSION SET WEEK_OF_YEAR_POLICY = 1;
SELECT 
    DATE_PART(Week, REPLACE(REPLACE(DATETIME,'AM',''),'PM','')::DATETIME) WEEK_COUNT,
    TO_CHAR(DATE_TRUNC('WEEK', DATETIME)::DATE, 'MM/DD/YYYY') AS WEEK_OF,
    STORE_NAME,
    PRODUCT_NAME,
    SUM(REWARDS_POINTS) AS TOTAL_REWARDS_POINTS
FROM SFC_ISDA.SFC_BRONZE.SFC_PLUS_CPOINTS
WHERE 
    TYPE = 'EARN'
    AND REPLACE(REPLACE(DATETIME,'AM',''),'PM','')::DATETIME > '10/1/2024'
GROUP BY 
    DATE_PART(Week, REPLACE(REPLACE(DATETIME,'AM',''),'PM','')::DATETIME),
    TO_CHAR(DATE_TRUNC('WEEK', DATETIME)::DATE, 'MM/DD/YYYY'),
    STORE_NAME,
    PRODUCT_NAME
ORDER BY WEEK_OF;


SELECT 
    PRODUCT_NAME,
    SUM(REWARDS_POINTS) AS TOTAL_REWARDS_POINTS
FROM SFC_ISDA.SFC_BRONZE.SFC_PLUS_CPOINTS
WHERE 
    TYPE = 'REDEEM'
GROUP BY 
    PRODUCT_NAME
ORDER BY TOTAL_REWARDS_POINTS DESC;


SELECT * FROM SFC_ISDA.SFC_BRONZE.EPT_STRFD_REGISTER_TRANS
LIMIT 10
    