select
    TO_CHAR(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', P.INITIATED_AT::TIMESTAMP_NTZ),'YYYY-MM-DD HH24:MI:SS') AS INITIATED_AT,
    TO_CHAR(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', P.PROCESSED_AT::TIMESTAMP_NTZ),'YYYY-MM-DD HH24:MI:SS') AS PROCESSED_AT,
    TO_CHAR(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', P.PARTIALLY_REFUNDED_AT::TIMESTAMP_NTZ),'YYYY-MM-DD HH24:MI:SS') AS PARTIALLY_REFUNDED_AT ,
    TO_CHAR(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', P.FULLY_REFUNDED_AT::TIMESTAMP_NTZ),'YYYY-MM-DD HH24:MI:SS') AS FULLY_REFUNDED_AT,
    C.NAME as PartnerName,
    P.REFERENCE_ID,
    P.AMOUNT,
    P.STATUS,
    P.REASON,
    A.FIRST_NAME,
    A.LAST_NAME,
    A.EMAIL_ADDRESS,
    A.MOBILE_NUMBER
from "BPAY_SFCPLUS_payments" P
    inner join "BPAY_SFCPLUS_clients" C on C.ID = P.CLIENT_ID
    left outer join "BPAY_SFCPLUS_accounts" A on P.ACCOUNT_ID = A.ID
WHERE C.NAME = :partnername and
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', P.INITIATED_AT::TIMESTAMP_NTZ)::DATE= :initiatedate

order by P.INITIATED_AT desc