SELECT
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) = CURRENT_DATE - 1 THEN 1 ELSE 0 END) AS DTD,
    SUM(CASE WHEN TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) BETWEEN DATE_TRUNC('WEEK', CURRENT_DATE) AND CURRENT_DATE-1 THEN 1 ELSE 0 END) AS WTD,
    -- SUM(CASE WHEN TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) BETWEEN DATE_TRUNC('WEEK', CURRENT_DATE - 7) AND DATE_TRUNC('WEEK', CURRENT_DATE) - 1 THEN 1 ELSE 0 END) AS WTD,
    SUM(CASE WHEN TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) BETWEEN DATE_TRUNC('MONTH', CURRENT_DATE) AND CURRENT_DATE THEN 1 ELSE 0 END) AS MTD,
    SUM(CASE WHEN TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) BETWEEN DATE_TRUNC('YEAR', CURRENT_DATE) AND CURRENT_DATE THEN 1 ELSE 0 END) AS YTD
FROM "BPAY_SFCPLUS_accounts"
WHERE TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) != CURRENT_DATE;