SELECT
    CONCAT(IFNULL(A.FIRST_NAME, ''), ' ', IFNULL(A.MIDDLE_NAME, ''), ' ', IFNULL(A.LAST_NAME, '')) AS FULL_NAME
    ,EMAIL
    ,A.MOBILE_NUMBER
    ,DATE_OF_BIRTH,
    TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', A.CREATED_AT::TIMESTAMP_NTZ)) AS DATE
FROM SFC_RWDS_ACCOUNTS A
        INNER JOIN SFC_PLUS_ACCOUNTS core ON A.id = core.rewards_id AND core.deleted_at IS NULL
WHERE
TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', A.CREATED_AT::TIMESTAMP_NTZ)) = :daterange
AND CURRENCY = 'CAD'
ORDER BY A.CREATED_AT DESC
