WITH PER_ACC AS ( -- PER_ACC: SHOWS PURCHASE DETAILS PER ACCOUNT, ADDED A TAG TO COUNT IF PRODUCT IS BEING PURCHASED BY OTHER ACCOUNTS/CUSTOMERS
    SELECT 
        BASK.ACCOUNT_ID,
        UPC.UPC,
        UPC.DESCRIPTION,
        COUNT(UPC.UPC) AS PURCHASE_COUNT,
        1 AS TAG
        
    FROM SFC_PLUS_UPC UPC
    
    INNER JOIN SFC_PLUS_TRANSACTIONS_BASKETSIZE BASK
    ON UPC.UPC = BASK.UPC_CODE
    
    WHERE BASK.AGE >= 30 AND BASK.AGE <= 39
    AND UPC.DEPARTMENT != 'PRODUCE'
    AND UPC.UPC NOT IN ('0060698859315',   -- T-Shirt Bag Multiuse
                        '0000000000055',   -- DINE IN
                        '0000000000016',   -- CRV less than 24o
                        '0000000000017',   -- CRV 24oz or More
                        '0017959414053')   -- Reusable Paper Bag
    
    GROUP BY
        BASK.ACCOUNT_ID,
        UPC.UPC,
        UPC.DESCRIPTION

    ORDER BY 
        BASK.ACCOUNT_ID,
        UPC.UPC,
        UPC.DESCRIPTION
),
CUMULATIVE AS ( -- CUMULATIVE: CALCULATES FOR THE CUMULATIVE TAG PER ITEM
    SELECT
        ACCOUNT_ID,
        UPC,
        DESCRIPTION,
        SUM(TAG) OVER(PARTITION BY UPC ORDER BY ACCOUNT_ID) AS CUMULATIVE_CNT
    
    FROM PER_ACC
)

SELECT
    UPC,
    DESCRIPTION, 
    MAX(CUMULATIVE_CNT) AS CUSTOMER_COUNT 

FROM CUMULATIVE 

GROUP BY 
    UPC,
    DESCRIPTION 

HAVING CUSTOMER_COUNT > 1 -- FILTERING TO > 1 TO MAKE SURE THAT ITEM IS BEING PURCHASED BY MULTIPLE ACCOUNTS/CUSTOMERS

ORDER BY CUSTOMER_COUNT DESC
;