WITH MAIN AS (
    SELECT
        -- HDR.PROC_DATE,
        -- HDR.DATETIME,
        -- HDR.EMP_NO,
        -- HDR.TILL_NO,
        -- HDR.REGISTER_NO,
        -- HDR.TRANS_NO,
        DISTINCT TRANS.UPC,
        CASE 
            WHEN RWDS.ID IS NOT NULL THEN 'Member'
            ELSE 'Non-Member'
        END AS MEMBER_STATUS,
        RWDS.CARD_NUMBER,
        CASE 
            WHEN RWDS.ID IS NOT NULL THEN DATEDIFF('YEAR', TRY_TO_DATE(RWDS.DATE_OF_BIRTH), TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', 
            CURRENT_DATE::TIMESTAMP_NTZ))) 
            ELSE 0
        END AS AGE,
        CASE
            WHEN AGE BETWEEN 18 AND 24 THEN 'GEN Z'
            WHEN AGE BETWEEN 25 AND 40 THEN 'MILLENIALS'
            WHEN AGE BETWEEN 41 AND 56 THEN 'GEN X'
            WHEN AGE >= 57 THEN 'BOOMERS'
            ELSE 'OTHERS'
        END AS BRACKET,
        -- TRANS.UPC,
        UPC.DESCRIPTION,
        1 AS TAG
    
    FROM EPT_STRFD_REGISTER_HEADER HDR
    
    INNER JOIN EPT_STRFD_REGISTER_TRANS TRANS
    ON HDR.PROC_DATE = TRANS.PROC_DATE
    AND HDR.DATETIME = TRANS.DATETIME
    AND HDR.EMP_NO = TRANS.EMP_NO
    AND HDR.TILL_NO = TRANS.TILL_NO
    AND HDR.REGISTER_NO = TRANS.REGISTER_NO
    AND HDR.TRANS_NO = TRANS.TRANS_NO
    
    INNER JOIN SFC_PLUS_UPC UPC
    ON TRANS.UPC = UPC.UPC
    
    LEFT JOIN SFC_RWDS_ACCOUNTS RWDS
    ON HDR.CUST_ID = RWDS.CARD_NUMBER

    WHERE MEMBER_STATUS = 'Member'
    AND BRACKET = 'GEN X'
    AND UPC.DEPARTMENT != 'PRODUCE'
    AND UPC.UPC NOT IN ('0060698859315',   -- T-Shirt Bag Multiuse
                        '0000000000055',   -- DINE IN
                        '0000000000016',   -- CRV less than 24o
                        '0000000000017',   -- CRV 24oz or More
                        '0017959414053')   -- Reusable Paper Bag
    
    -- HDR.PROC_DATE = '11/1/2024 12:00:00 AM'
    -- AND HDR.DATETIME = '11/1/2024 8:37:46 AM'
    -- AND HDR.EMP_NO = '902'
    -- AND HDR.TILL_NO = '6'
    -- AND HDR.REGISTER_NO = '6'
    -- AND HDR.TRANS_NO = '4'
),
CUMULATIVE AS ( -- CUMULATIVE: CALCULATES FOR THE CUMULATIVE TAG PER ITEM
    SELECT
        CARD_NUMBER,
        UPC,
        DESCRIPTION,
        SUM(TAG) OVER(PARTITION BY UPC, DESCRIPTION ORDER BY CARD_NUMBER) AS CUMULATIVE_CNT
    
    FROM MAIN
)

SELECT 
    UPC,
    DESCRIPTION, 
    MAX(CUMULATIVE_CNT) AS CUSTOMER_COUNT 

FROM CUMULATIVE 

GROUP BY 
    UPC,
    DESCRIPTION 

HAVING CUSTOMER_COUNT > 1 -- FILTERING TO > 1 TO MAKE SURE THAT ITEM IS BEING PURCHASED BY MULTIPLE ACCOUNTS/CUSTOMERS

ORDER BY CUSTOMER_COUNT DESC
;