WITH MAIN AS (
    SELECT 
        BASK.STORE_NAME,
        BASK.SOURCE,
        BASK.ACCOUNT_ID,
        -- TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', BASK.DATETIME::TIMESTAMP_NTZ)) AS TRX_DATE,
        BASK.ID,
        SUM(BASK.PRICE) AS SPEND
        
    FROM SFC_PLUS_TRANSACTIONS_BASKETSIZE BASK
    
    WHERE BASK.SOURCE = 'INSTORE'
    AND BASK.TYPE IN ('EARN', 'REDEEM')
    
    GROUP BY   
        BASK.STORE_NAME,
        BASK.SOURCE,
        BASK.ACCOUNT_ID,
        -- TRX_DATE,
        BASK.ID
)

SELECT 
    STORE_NAME,
    SOURCE,
    AVG(SPEND) AS AVG_SPEND

FROM MAIN

GROUP BY 
    STORE_NAME,
    SOURCE

ORDER BY STORE_NAME
;
