WITH MAIN AS (
    SELECT 
         BASK.STORE_NAME,
         BASK.SOURCE,
         BASK.ID,
         COUNT(*) AS BASKET_SIZE
         
    FROM SFC_PLUS_TRANSACTIONS_BASKETSIZE BASK
    
    WHERE BASK.SOURCE = 'INSTORE'
    AND BASK.TYPE IN ('EARN', 'REDEEM')
    
    GROUP BY    
        BASK.STORE_NAME,
        BASK.SOURCE,
        BASK.ID
)

SELECT 
    STORE_NAME,
    SOURCE,
    AVG(BASKET_SIZE) AS AVG_BASKET_SIZE

FROM MAIN

GROUP BY 
    STORE_NAME,
    SOURCE

ORDER BY STORE_NAME
;