WITH MAIN AS (
    SELECT 
     BASK.SOURCE,
     BASK.ID,
     COUNT(*) AS BASKET_SIZE
         
    FROM SFC_PLUS_TRANSACTIONS_BASKETSIZE BASK
    
    WHERE BASK.SOURCE = 'INSTORE'
    AND BASK.TYPE IN ('EARN', 'REDEEM')
    
    GROUP BY    
        BASK.SOURCE,
        BASK.ID
)

SELECT 
    SOURCE,
    AVG(BASKET_SIZE) AS AVG_BASKET_SIZE

FROM MAIN

GROUP BY SOURCE
;
