SELECT 
     AREA.AREA_CODE,
     AREA.COUNTRY,
     AREA.REGION,
     AREA.REGION2,
     COUNT(DISTINCT PACCS.ID) AS USERS,
    TO_DECIMAL((COUNT(*) / SUM(COUNT(*)) OVER()) * 100, 10, 2) AS "PERCENTAGE %"
     
FROM SFC_PLUS_ACCOUNTS PACCS

LEFT JOIN SFC_RWDS_ACCOUNTS RACCS
ON PACCS.REWARDS_ID = RACCS.ID 

LEFT JOIN SFC_PLUS_SFC_NORTH_AMERICA_AREA_CODES AREA
ON LEFT(PACCS.MOBILE_NUMBER, 3) = AREA.AREA_CODE

WHERE PACCS.MOBILE_NUMBER_COUNTRY_CODE = '1'

GROUP BY
     AREA.AREA_CODE,
     AREA.COUNTRY,
     AREA.REGION,
     AREA.REGION2

ORDER BY
    AREA.COUNTRY, 
    AREA.REGION, 
    AREA.AREA_CODE
;
