SELECT 
    CASE 
        WHEN PACCS.BIRTH_DATE IS NULL THEN 'NO BIRTH DATE SPECIFIED'
        WHEN DATEDIFF('YEAR', PACCS.BIRTH_DATE, TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CURRENT_DATE::TIMESTAMP_NTZ))) < 20 THEN 'BELOW 20'
        WHEN DATEDIFF('YEAR', PACCS.BIRTH_DATE, TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CURRENT_DATE::TIMESTAMP_NTZ))) BETWEEN 20 AND 29 THEN '20+'
        WHEN DATEDIFF('YEAR', PACCS.BIRTH_DATE, TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CURRENT_DATE::TIMESTAMP_NTZ))) BETWEEN 30 AND 39 THEN '30+'
        WHEN DATEDIFF('YEAR', PACCS.BIRTH_DATE, TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CURRENT_DATE::TIMESTAMP_NTZ))) BETWEEN 40 AND 49 THEN '40+'
        WHEN DATEDIFF('YEAR', PACCS.BIRTH_DATE, TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CURRENT_DATE::TIMESTAMP_NTZ))) >= 50 THEN '50+'
    END AS AGE_GROUP,
    COUNT(DISTINCT PACCS.ID) AS USERS,
    TO_DECIMAL((COUNT(*) / SUM(COUNT(*)) OVER()) * 100, 10, 2) AS "PERCENTAGE %"

FROM SFC_PLUS_ACCOUNTS PACCS

LEFT JOIN SFC_RWDS_ACCOUNTS RACCS
ON PACCS.REWARDS_ID = RACCS.ID 

WHERE PACCS.MOBILE_NUMBER_COUNTRY_CODE = '1' 

GROUP BY AGE_GROUP

ORDER BY 
    CASE 
        WHEN AGE_GROUP = 'BELOW 20' THEN 1
        WHEN AGE_GROUP = '20+' THEN 2
        WHEN AGE_GROUP = '30+' THEN 3
        WHEN AGE_GROUP = '40+' THEN 4
        WHEN AGE_GROUP = '50+' THEN 5
        WHEN AGE_GROUP = 'NO BIRTH DATE SPECIFIED' THEN 6
    END
;