SELECT
    CONCAT(IFNULL(a.FIRST_NAME, ''), ' ', IFNULL(a.MIDDLE_NAME, ''), ' ', IFNULL(a.LAST_NAME, '')) AS FULL_NAME
    ,a.EMAIL
    ,a.MOBILE_NUMBER
    ,a.DATE_OF_BIRTH,
    TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', a.CREATED_AT::TIMESTAMP_NTZ)) AS DATE
FROM SFC_ISDA.SFC_BRONZE.SFC_RWDS_ACCOUNTS A    
    INNER JOIN SFC_ISDA.SFC_BRONZE.SFC_PLUS_ACCOUNTS core ON A.id = core.rewards_id AND core.deleted_at IS NULL
WHERE
TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', a.CREATED_AT::TIMESTAMP_NTZ)) = :daterange
AND CURRENCY = 'USD'
    AND a.ID NOT IN (
                        '084c35ba-4e90-4cf9-96e6-ffb399c4646b',
                        '204e44d5-87a0-474b-9a58-32015fc5301a'
                        ) -- EXCLUDING SEAFOOD CITY MASTER AND SEAFOOD CITY CANADA
ORDER BY a.CREATED_AT DESC