CREATE OR REPLACE NOTIFICATION INTEGRATION SFC_PLUS_ALERTS
    TYPE = EMAIL
    ENABLED = TRUE
    ALLOWED_RECIPIENTS = ('rdiocos@agsx.net','jdean@agsx.net','cpalma@agsx.net','rgajardo@agsx.net');

CREATE OR REPLACE ALERT SFC_PLUS_TASK_ALERT
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 40 * * * * UTC'
    IF (EXISTS (SELECT 
        NAME AS TASK_NAME,
        TO_CHAR(COMPLETED_TIME, 'YYYY-MM-DD HH24:MI') AS COMPLETED_TIME_NO_SECONDS,
        STATE AS CURRENT_STATE
        FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
        WHERE STATE = 'FAILED' AND
        NAME IN ('SFC_PLUS_TRUNCATE_TASK', 'SFC_PLUS_IIS_TASK', 'ALTER_SESSION_TASK')
        AND COMPLETED_TIME_NO_SECONDS = ABS(
        TO_TIMESTAMP(TO_CHAR(COMPLETED_TIME, 'YYYY-MM-DD HH24:MI'), 'YYYY-MM-DD HH24:MI') 
        - CURRENT_TIMESTAMP)
        ORDER BY COMPLETED_TIME DESC))
        THEN CALL SYSTEM$SEND_EMAIL(
            'SFC_PLUS_ALERTS',
            'rdiocos@agsx.net,jdean@agsx.net,cpalma@agsx.net,rgajardo@agsx.net',
            'TASK FAILED',
            'SFC_PLUS_TASK FAILED:' || ERROR_MESSAGE());

ALTER ALERT SFC_PLUS_TASK_ALERT RESUME;
SHOW ALERTS;

select * from SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
where state = 'SUCCEED'
order by COMPLETED_TIME desc