CREATE OR REPLACE NOTIFICATION INTEGRATION SFC_RWRDS_ALERTS
    TYPE = EMAIL
    ENABLED = TRUE
    ALLOWED_RECIPIENTS = ('rdiocos@agsx.net','jdean@agsx.net','cpalma@agsx.net','rgajardo@agsx.net');

    //OWNED BY ACCOUNT_ADMIN
CREATE OR REPLACE ALERT SFC_RWRDS_TASK_ALERT
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 40 * * * * UTC'
    IF (EXISTS (SELECT 
        NAME AS TASK_NAME,
        TO_CHAR(COMPLETED_TIME, 'YYYY-MM-DD HH24:MI') AS COMPLETED_TIME_NO_SECONDS,
        STATE AS CURRENT_STATE
        FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
        WHERE STATE = 'FAILED' AND
        NAME IN ('SFC_RWDS_TRUNCATE_TASK', 'SFC_RWDS_IIS_TASK', 'ALTER_SESSION_RWDS_TASK')
        AND ABS(
        TO_TIMESTAMP(TO_CHAR(COMPLETED_TIME, 'YYYY-MM-DD HH24:MI'), 'YYYY-MM-DD HH24:MI') 
        - CURRENT_TIMESTAMP
    ) = (
        SELECT MIN(ABS(
                TO_TIMESTAMP(TO_CHAR(COMPLETED_TIME, 'YYYY-MM-DD HH24:MI'), 'YYYY-MM-DD HH24:MI')
                - CURRENT_TIMESTAMP
            ))
        FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
        WHERE STATE = 'FAILED'
          AND NAME IN ('SFC_RWDS_TRUNCATE_TASK', 'SFC_RWDS_IIS_TASK', 'ALTER_SESSION_RWDS_TASK')
    )
        ORDER BY COMPLETED_TIME DESC))
        THEN CALL SYSTEM$SEND_EMAIL(
            'SFC_RWRDS_ALERTS',
            'rdiocos@agsx.net,jdean@agsx.net,cpalma@agsx.net,rgajardo@agsx.net',
            'TASK FAILED',
            'SFC_RWDS_TASK FAILED');

ALTER ALERT SFC_RWRDS_TASK_ALERT RESUME;

ALTER ALERT SFC_RWRDS_TASK_ALERT SUSPEND;
//USE ACCOUNT_ADMIN ROLE
SHOW ALERTS;