(
SELECT
        CAST(TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) AS VARCHAR) AS Date,
        TO_CHAR(COUNT(*), 'FM999,999,999') AS "Registration Count"
    FROM SFC_PLUS_ACCOUNTS
    WHERE
        TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) != CAST(CONVERT_TIMEZONE('America/Los_Angeles', CURRENT_TIMESTAMP) AS DATE)
        AND TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) = :DailyRegis
    GROUP BY
        TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ))
)
UNION ALL
(
    SELECT
        'TOTAL' AS Date,
        TO_CHAR(COUNT(*), 'FM999,999,999') AS "Registration Count"
    FROM SFC_PLUS_ACCOUNTS
    WHERE
        TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) != CAST(CONVERT_TIMEZONE('America/Los_Angeles', CURRENT_TIMESTAMP) AS DATE)
        AND TO_DATE(CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', CREATED_AT::TIMESTAMP_NTZ)) = :DailyRegis
)
ORDER BY
    CASE WHEN Date = 'TOTAL' THEN 1 ELSE 0 END,
    Date DESC;