SELECT 
    *
FROM SFC_TOP_USERS_BY_TRANSACTIONS
    PIVOT(COUNT(TRANSACTION_COUNT_PIVOT) FOR CONVERTED_DATE IN (ANY ORDER BY CONVERTED_DATE DESC)
        DEFAULT ON NULL (0))
WHERE
    FIRST_NAME = :FIRST_NAME AND
    LAST_NAME = :LAST_NAME AND
    ACCOUNT_ID = :ACCOUNT_ID 
ORDER BY TRANSACTION_COUNT DESC;